# Generated by Django 5.0.2 on 2024-05-04 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='people_required',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('people_required', models.IntegerField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='commissions.commission')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='commissions.job')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
