# Generated by Django 5.0.2 on 2024-05-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_remove_commission_people_required_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Full'), ('C', 'Completed'), ('D', 'Discontinued')], default='O', max_length=1),
        ),
    ]
