# Generated by Django 5.0.2 on 2024-05-05 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commission_owner_alter_job_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='commission',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='commissions.commission'),
        ),
    ]
