# Generated by Django 5.0.2 on 2024-05-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_remove_job_application_job_application_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_Application',
            new_name='JobApplication',
        ),
    ]
