# Generated by Django 5.0.2 on 2024-05-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_rename_owner_commission_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='commission',
            new_name='owner',
        ),
    ]
