# Generated by Django 5.0.2 on 2024-05-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_remove_jobapplication_job_jobapplication_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Full')], default='O', max_length=1),
        ),
    ]
